feat(krt): Create KRT library
konstellation-io/krt pull request #1
Opened 2023-06-05 18:23 UTC by alexrodfe

DRAFT

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-06-08 06:40 UTC, dfinteligenz requested changes
LGTM! Just added a pair of comments.

2023-06-08 06:40 UTC, dfinteligenz commented on .github/workflows/test-krt.yaml
> +  workflow_dispatch:
The workflow dispatch won't be needed for this workflow, as it should always be executed when opening a PR or merging to main or dev.

2023-06-08 06:40 UTC, dfinteligenz commented on .github/workflows/utils-pr-size-labeler.yaml
> +            "*.work.sum"
These two patterns are not needed, as the repository is not a monorepo

2023-06-08 06:40 UTC, dfinteligenz commented on README.md
> +Write this documentation
Remove this todo list from the PR.

2023-06-08 06:42 UTC, dfinteligenz commented
Also, you need to fix the indentation to match the one on the KAI project.

You can add the next file as `.editorconfig` in the root of the repo.

```
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
charset = utf-8

[{Makefile,go.mod,go.sum,*.go}]
indent_style = tab

[*.py]
indent_size = 4
trim_trailing_whitespace = true
max_line_length = 119
```

2023-06-09 12:11 UTC, JYisus requested changes

2023-06-09 12:11 UTC, JYisus commented on pkg/errors/errors_test.go
> +package errors
IMO, we should define tests in the package _test (errors_test), to avoid calls to private functions

2023-06-09 12:11 UTC, JYisus commented on pkg/krt/krt_builder_test.go
> +//go:build unit
maybe we should move this to a package testhelpers or something like that

2023-06-09 12:11 UTC, JYisus commented on pkg/krt/validations_test.go
> +package krt
Same with this package name

2023-06-09 13:58 UTC, dfinteligenz requested changes
LGTM, the only thing we need to fix is the indentation problem.

All new files are tab indented except for the errors file, which is space indented.

2023-06-09 14:04 UTC, alexrodfe commented on pkg/errors/errors_test.go
> +package errors
I thought having them in another package disrupted coverage metrics. I have done a check in my local and coverage is still functioning, so I agree we should have them in different packages as to avoid calling private functions and possible future import cycles.
I'll have these changes done for the next PR coming for this package, as this development wise is much easier for me.

2023-06-09 14:14 UTC, dfinteligenz approved these changes

2023-06-09 14:31 UTC, merged