feat: use only protocol in networking
konstellation-io/krt pull request #10
Opened 2023-06-21 15:40 UTC by alexrodfe

## Description

Deprecate DestinationProtocol and TargetProtocol in favor of a single "Protocol" variable. 

## Motivation and Context

Kubernetes does only need 1 protocol config that applies to both ends.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [X] I have created tests for my code changes, and the tests are passing.
- [X] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-06-21 17:34 UTC, JYisus approved these changes

2023-06-22 06:50 UTC, dfinteligenz commented on pkg/parse/test_files/missing_defaults_krt.yaml
> -          destinationProtocol: 'UDP'
Shouldn't this be replaced by `protocol: 'UDP'`?

2023-06-22 06:51 UTC, dfinteligenz requested changes

2023-06-22 06:51 UTC, dfinteligenz commented on pkg/parse/test_files/missing_defaults_krt.yaml
> -          destinationProtocol: 'UDP'
Shouldn't this be replaced by `protocol: 'UDP'`?

2023-06-22 08:41 UTC, alexrodfe commented on pkg/parse/test_files/missing_defaults_krt.yaml
> -          destinationProtocol: 'UDP'
No need, this krt file is made in a way that forces default set in some processes. I just changed the default set of the protocol to the first process so test logic is more simple.

2023-06-22 08:43 UTC, dfinteligenz approved these changes

2023-06-22 09:09 UTC, merged