feat: add resources management validations
konstellation-io/krt pull request #15
Opened 2023-07-25 10:25 UTC by alexrodfe

## Description

TODO

## Motivation and Context

TODO

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other changes (ci configuration, documentation or any other kind of changes)

## Checklist:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).
- [ ] I have updated the documentation accordingly.

2023-07-26 14:30 UTC, kafkaphoenix commented on pkg/krt/krt_builder_test.go
> +							CPU: &krt.ProcessCPU{
in my examples i was using for memory Mi is M similar?

2023-07-26 14:32 UTC, kafkaphoenix submitted a review, later dismissed

2023-07-26 14:33 UTC, alexrodfe commented on pkg/krt/krt_builder_test.go
> +							CPU: &krt.ProcessCPU{
Kubernetes accepts both M and Mi, and all other measurements.
The difference between M and Mi is that M is x1000 and Mi is x1024 . More bit-wise correct (power of 2)

2023-07-27 09:38 UTC, dfinteligenz requested changes

2023-07-27 09:38 UTC, dfinteligenz commented on pkg/errors/errors.go
> +var ErrInvalidProcessCPU = errors.New("invalid process CPU, must be of form '1', '0.5' or '100m'")
This should reference that the CPU value is for the limit somewhere.

Maybe change it to:
```suggestion
var ErrInvalidProcessCPULimits = errors.New("invalid process CPU limit value, must be of form '1', '0.5' or '100m'")
```

2023-07-27 09:38 UTC, dfinteligenz commented on pkg/errors/errors.go
> +var ErrInvalidProcessCPURelation = errors.New("invalid process CPU relation, 'limit' cannot be lower than 'request'")
```suggestion
var ErrInvalidProcessCPURelation = errors.New("invalid process CPU, 'limit' cannot be lower than 'request'")
```

2023-07-27 09:38 UTC, dfinteligenz commented on pkg/errors/errors.go
> +var ErrInvalidProcessMemory = errors.New("invalid process memory, must be of form '350M' or '1Gi'")
Same as CPU, we should reference that this is a resource limit value somewhere in the message.

```suggestion
var ErrInvalidProcessMemory = errors.New("invalid process memory limit, must be of form '350M' or '1Gi'")
```

2023-07-27 09:38 UTC, dfinteligenz commented on pkg/errors/errors.go
> +var ErrInvalidProcessMemoryRelation = errors.New("invalid process memory relation, 'limit' cannot be lower than 'request'")
```suggestion
var ErrInvalidProcessMemoryRelation = errors.New("invalid process memory, 'limit' cannot be lower than 'request'")
```

2023-07-27 09:38 UTC, dfinteligenz commented on pkg/krt/krt.go
> +}
These two types could be replaced by a generic ResourceLimits struct
```suggestion
type ResourceLimit struct {
	Request string `yaml:"request"`
	Limit   string `yaml:"limit"`
}

type ProcessResourceLimits struct {
	CPU    *ResourceLimit    `yaml:"CPU"`
	Memory *ResourceLimit `yaml:"memory"`
}
```

2023-07-27 09:41 UTC, alexrodfe commented on pkg/errors/errors.go
> +var ErrInvalidProcessCPU = errors.New("invalid process CPU, must be of form '1', '0.5' or '100m'")
This error refers to both the limit and request variables

2023-07-27 09:42 UTC, alexrodfe commented on pkg/errors/errors.go
> +var ErrInvalidProcessMemory = errors.New("invalid process memory, must be of form '350M' or '1Gi'")
Ditto, refers to both values

2023-07-27 09:43 UTC, alexrodfe commented on pkg/krt/krt.go
> +}
Good catch

2023-07-27 10:14 UTC, kafkaphoenix approved these changes
Good work!

2023-07-27 10:15 UTC, dfinteligenz commented on pkg/errors/errors.go
> +var ErrInvalidProcessCPU = errors.New("invalid process CPU, must be of form '1', '0.5' or '100m'")
Yep, but both limit and requests are resource limits

2023-07-27 10:30 UTC, kafkaphoenix approved these changes

2023-07-27 10:30 UTC, dfinteligenz submitted a review, later dismissed

2023-07-27 10:46 UTC, kafkaphoenix approved these changes

2023-07-27 10:47 UTC, merged